### ISSUE TITLE
Obtain digests for tx kernel functions exposed in Rust Miden SDK

### ISSUE THREAD

**Issue by greenhat** [0xPolygonMiden/compiler#143]
### Goal
To publish the Rust Miden SDK crates #138 we need to hard-code the digests for all exposed functions (tx kernel, stdlib, etc.).

### Implementation
The first thing that comes to mind is to compile their MASM and pull the digests out of it.

**Comment by greenhat** [comment]
@bitwalker Since we intend to link the real tx kernel (from `miden-base`) instead of our stubs at https://github.com/0xPolygonMiden/compiler/blob/5c5fae40380a89c19768431c0632db91e24127da/midenc-session/src/libs.rs#L83-L84 
I don't see any reason to bundle digests with bindings anymore. We can close this issue and make a new one for the real tx kernel linking. What do you think?

**Comment by bitwalker** [comment]
Agreed, I think we have all we need now to obtain the digests from package metadata, rather than having to hardcode them. Once we have type signatures in MASM, we should be able to generate the actual `extern` bindings automatically, and all we'd need to do is define higher-level wrappers. We should be able to automatically apply ABI transformation rules in that case as well.

For now though, we at least have the real digests available to use.

**Comment by greenhat** [comment]
Closed in favor of #307
