### ISSUE TITLE
Repo naming and structure

### ISSUE THREAD

**Issue by bobbinth** [0xPolygonMiden/compiler#20]
The ultimate compilation pipeline we are trying to achieve looks something like this:
```
Rust -> WASM -> MidenIR -> MASM
```
The code in this repo handles the last 3 steps (`WASM -> MASM`). This leads to a couple of questions:

1. Where should `Rust -> WASM` step live and what components could it include?
2. Is `miden-ir` really the right name for this repo?

It seems to me that the answer to the second question is no. This repo contains much more than just IR - so, we should rename it to something more relevant. `miden-compiler` is one option - but happy to hear other suggestions.

As for the first question, it seems to me that this should live in a separate repo. That repo could probably consist of several crates covering the following functionality:
1. Cargo extension which would use crates from this repo internally.
2. A set of macros we'd need to shape the Rust code.
3. A set of wrapper libraries around Miden `stdlib` and `midenlib` libraries (ideally, with a tool which can generate these wrappers automatically).
4. Probably something else I'm not thinking of.

As for the name for this repo (and associated crates) - I think it could be something unique (i.e., doesn't have to include "miden" in the name). I don't have great ideas on this yet - so, any suggestions are welcome. A couple of examples from other projects:

- Aribtrum has Stylus
- Fuel Labs has Forc

One other question: should this new repo try to support general compilation from Rust to MASM or be focused specifically on the rollup? My thinking is that we should focus it on the rollup. This would reduce the scope of what we need to do and will help us get to Miden smart contracts in Rust faster.

**Comment by bitwalker** [comment]
In the short term `miden-compiler` (or `compiler`) is probably a better name for this repo. I'm down to give it a codename as well, in the vein of Stylus/Forc, though I don't know if we have a particular theme or whatever that we want to use for those. If we do, let me know what it is and I can try and come up with some ideas.

As for the Rust frontend, I think we'll want a repo that contains the Cargo extension (which pulls in the compiler as a library to do the actual compilation) and the proc macros we rely on to actually do compilation. The rest I think we'll want to have in separate repos per library, but there might be cases where grouping them is beneficial.

> One other question: should this new repo try to support general compilation from Rust to MASM or be focused specifically on the rollup? My thinking is that we should focus it on the rollup. This would reduce the scope of what we need to do and will help us get to Miden smart contracts in Rust faster.

I think the Cargo extension should do both, but the repo itself could be more rollup-oriented for sure. General compilation from Rust is going to be easier to implement than the rollup, which has additional complexities, so it's probably better to get at least the basics of that working before we jump into the rollup bits, since any issues we hit there will necessarily affect the rollup as well.

**Comment by bobbinth** [comment]
I've renamed the repo to just "compiler" and changed the description to "Compiler from MidenIR to Miden Assembly" (but let me know if it should be something else).

In this repo, we probably should do the following:
- Update the main readme file to reflect the change.
- Maybe move up `midenc` from tools to the root level.

Btw, after I renamed the repo, I thought that maybe a better name for it would have been `midenc`? If you guys think it is better than just `compiler`, I'm happy to rename.

**Comment by dav8t** [comment]
Reg. https://github.com/0xPolygonMiden/compiler/issues/20#issue-1886557807 

Interestingly, I too had been already thinking of having a more generalist/friendly name for my pet project that I also wanted to work with Miden and had these in my mind; which is as below :

**Palette**: as in, it is analogical to the [palette](https://en.wikipedia.org/wiki/Palette_(painting)) with which the developer is like an artist and they can mix and paint(code/smart contracts) with different colours
**Stencil**: Just like the above, the analogy here is the "[stencil](https://en.wikipedia.org/wiki/Stencil)" with which the developer can easily produce designs(code/smart contracts) using the intermediate object with holes(intermediate representation/code templates)

It immediately clicked for me on seeing this discussion popping up :)

**Comment by dav8t** [comment]
The idea behind these names is to have sort of a(smart contract)development environment that is more relatable and appealing in a general sense.

**Comment by bitwalker** [comment]
> In this repo, we probably should do the following:
>
> * Update the main readme file to reflect the change.

I'll do this along with the other changes to the readme in my docs PR that will be opened today/tomorrow.

> * Maybe move up midenc from tools to the root level.

Yeah I'll move it out of `tools/` and into the root at least.

> Btw, after I renamed the repo, I thought that maybe a better name for it would have been midenc?

I could go either way, but `compiler` is a bit more descriptive for those who won't automatically recognize that `midenc` follows the naming convention for compiler executables (e.g. `rustc`, `cc`, `erlc`, etc.). I'll leave it up to you though if you have a preference!

@dav8t Naming is always my least favorite part of building a new project 😅. We'll probably stick to keeping it simple for now, e.g. "the Miden compiler"/"midenc", rather than use a code name of some kind - but if we come up with a good one, that could always change!

**Comment by bitwalker** [comment]
I think this issue is largely resolved now, but if further changes/discussion are needed, feel free to reopen or start a new issue, whichever is appropriate.
