### ISSUE TITLE
Create WASM compilation example(s)

### ISSUE THREAD

**Issue by bobbinth** [0xPolygonMiden/compiler#81]
Would be good to create an example (or maybe a couple) showing how we can compile WASM files to MASM files. The basic example could include something simple - like computing a fixed Fibonacci number. We could add to these examples over time to include more complex use cases.

The examples could be in a separate top-level directory (e.g., `examples`)  with a short README explaining how to compile them.

The main goal here is to make it easy for newcomers to see how compilation works and check out the output of the compiler for some simple programs.

**Comment by gubloon** [comment]
@bobbinth For examples, shouldn't it be about Rust to MASM? Because a developer is going to be more interested on learning how "compilation from a high level language to MASM" works and less on how it works with WASM to MASM.
And when we include an example on Rust to MASM compilation, it is going to include WASM to MASM part anyway.

**Comment by bobbinth** [comment]
> shouldn't it be about Rust to MASM?

Eventually, yes - but for now we can start simpler and show Wasm to MASM.

**Comment by bitwalker** [comment]
This is closed via #91, which covers compiling Rust->Wasm and Wasm->Masm. The current process is not great, but isn't too complicated, but there are a few things I need to address to streamline the process a bit. The frontend changes that @greenhat is working on are going to change things as well, though I expect much of that will be a separate process with its own guide, rather than replacing the ones in that PR. In any case, we'll want to get GitHub pages set up for this repo when we can (I don't believe anyone but @bobbinth can do that currently, but hopefully we can push updates automatically once set up).
